### ISSUE TITLE
Support React fragments

### ISSUE THREAD

**Issue by garrypolley** [Crownpeak/DXM-React-SDK#14]
Simplified version

```jsx
const Hero = (props: any) => {
    CmsDataCache.setComponent("SingleHeadingSplitParagraph");

    const ctaText = new CmsField('ctaText', CmsFieldTypes.TEXT, props.ctaText)
    const ctaUrl = new CmsField('ctaUrl', CmsFieldTypes.HREF, props.ctaUrl)
    

    if (ctaText.value && ctaUrl.value) {
        ctaSection = (
            <div className="col-span-6 col-start-2 mt-5 md:pl-6">
                {/* @ts-ignore */}
                <a href={ctaUrl}><button className="btn w-full h-12 text-2xl font-bold p-0 m-0">{ctaText}</button></a>
            </div>
        )
    }

    return (
       <div>
            <h1> A title</h1>
            <p>Some Text</p>
            {ctaSection}
       </div>
   )
}
```

What is the recommended way to handle this interaction. Ideally the CTA does not display whenever there is not a CTA configured. 

I'd expect the editor to go into the form edit view in CrownPeak to configure the `ctaText` and `ctaUrl`.

**Comment by garrypolley** [comment]
The error was from a different part of code. 

I'm attempting to do somethign like: 

```
{{ctaText.value && ctaUrl.value && 
                            <div className="col-span-6 col-start-2 mt-5 md:pl-6">
                                <a href={ctaUrl:Href}><button className="btn w-full h-12 text-2xl font-bold p-0 m-0">{ctaText:text}</button></a>
                            </div>
                            }}
```

The fragment is used in the else of a `cp-scaffold` and works fine.

**Comment by richard-lund** [comment]
This is why we created the cp-scaffold option. There are many ways to write code, and we can't support everything. Therefore, for simplicity, we opted to only process the return value.

If you have a specific use-case where this can't be done, or where it really seems not to fit, please let me know.
