### ISSUE TITLE
Support for boolean CMS field type

### ISSUE THREAD

**Issue by garrypolley** [Crownpeak/DXM-React-SDK#16]
Looking at https://github.com/Crownpeak/DXM-React-SDK#cmsfieldtype

It appears the boolean (checkbox in the UI) field is not supported yet. Are there plans to support this type? 

Can this be accomplished today by doing something like: 

```jsx

return (
    /* cp-scaffold */
    {MyField:Checkbox}
   /* /cp-scaffold */
)
```

**Comment by richard-lund** [comment]
@garrypolley - I've raised issue #83 on the SDK Core repo (see https://github.com/Crownpeak/DXM-SDK-Core/issues/83) to cover this request because it's not specific to the React SDK.

I'll close this one - please watch the other one for updates.
